#!/bin/bash
echo "(Ôo)' > 1-confused_smiley[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D["[D[D[D[D[D[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[D[D[D[D
